name: Build Failure Notifications
on:
  check_suite:
    types: [completed]

permissions:
  contents: read
  id-token: write
  checks: read

jobs:
  notify:
    runs-on: github-ubuntu-latest-s # Public GitHub hosted runner required, Self-Hosted runners do not support Docker-in-Docker
    permissions:
      id-token: write
    if: failure()
    steps:
      - name: Notify Slack of Build Failure
        uses: ./.github/actions/slack-notify
        with:
          slack_channel: 'squad-ide-mcp-server-bots'
          slack_title: 'Build Failed'
          slack_message: |
            Workflow failed in ${{ github.repository }} 🚨
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            Branch: ${{ github.event.workflow_run.head_branch }}
          slack_color: 'danger'
