name: Build
on:
  push:
    branches:
      - master
      - branch-*
      - dogfood-*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}

# Required permissions for Vault OIDC and repo operations
permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: github-ubuntu-latest-s  # Required for public repositories
    name: Build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Build extension
        run: cargo build
      - name: Get Repox Credentials from Vault
        id: secrets
        uses: SonarSource/vault-action-wrapper@v3
        with:
          secrets: |
            development/kv/data/sonarcloud token | SQC_EU_TOKEN;
            development/kv/data/sonarcloud url | SQC_EU_URL;
      - name: SQC-EU Scan
        uses: SonarSource/sonarqube-scan-action@v6.0.0
        env:
          SONAR_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault).SQC_EU_TOKEN }}
          SONAR_REGION: eu
        with:
          args: >
            -Dsonar.organization=sonarsource
