name: Release Slack notification
on:
  release:
    types:
      - published

permissions:
  contents: read
  id-token: write
  checks: read

jobs:
  notify:
    runs-on: github-ubuntu-latest-s # Public GitHub hosted runner required, Self-Hosted runners do not support Docker-in-Docker
    permissions:
      id-token: write
    steps:
      - name: Vault Secrets
        id: secrets
        uses: SonarSource/vault-action-wrapper@v3
        with:
          secrets: |
            development/kv/data/slack token | SLACK_TOKEN;

      - name: Slack Notification rtCamp
        uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2.3.3
        env:
          SLACK_TOKEN: >-
            ${{ fromJSON(steps.secrets.outputs.vault).SLACK_TOKEN }}
          SLACK_CHANNEL: squad-ide-mcp-server
          SLACK_TITLE: Successful Release
          SLACK_MESSAGE: |
            Successfully released ${{ github.repository }}

          SLACK_USERNAME: BuildBot
          SLACK_COLOR: danger
---
name: Build Failure Notifications
on:
  check_suite:
    types: [completed]

permissions:
  contents: read
  id-token: write
  checks: read

jobs:
  notify:
    runs-on: github-ubuntu-latest-s # Public GitHub hosted runner required, Self-Hosted runners do not support Docker-in-Docker
    permissions:
      id-token: write
    if: failure()
    steps:
      - name: Vault Secrets
        id: secrets
        uses: SonarSource/vault-action-wrapper@v3
        with:
          secrets: |
            development/kv/data/slack token | SLACK_TOKEN;

      - name: Slack Notification rtCamp
        uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2.3.3
        env:
          SLACK_TOKEN: >-
            ${{ fromJSON(steps.secrets.outputs.vault).SLACK_TOKEN }}
          SLACK_CHANNEL: squad-ide-mcp-server-bots
          SLACK_TITLE: Build Failed
          SLACK_MESSAGE: |
            Workflow failed in ${{ github.repository }} 🚨
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            Branch: ${{ github.event.workflow_run.head_branch }}

          SLACK_USERNAME: BuildBot
          SLACK_COLOR: danger
